### NUMPY

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### 1D Array

In [2]:
a=np.array([10,20,30,50,60,0])
a

array([10, 20, 30, 50, 60,  0])

#### dtype

In [3]:
a.dtype

dtype('int32')

#### shape

In [4]:
a.shape

(6,)

#### dimension

In [5]:
a.ndim

1

#### size

In [6]:
a.size

6

In [7]:
a[0]

10

In [8]:
a[2]

30

### MULTI DIMENSIONAL  ARRAY

In [9]:
a_2d=np.array([[10,20,30,],[23,25,27]])
a_2d

array([[10, 20, 30],
       [23, 25, 27]])

In [10]:
a_4d=np.array([[10,20,30,40],[10,20,30,40]])

In [11]:
a_2d.dtype

dtype('int32')

In [12]:
a_2d.shape

(2, 3)

In [13]:
a_2d.ndim

2

In [14]:
a_2d.size

6

In [15]:
a_2d[0]

array([10, 20, 30])

In [16]:
a_2d[1][0]

23

## Another type of multi dimensional arrays

In [17]:
another_type_array=np.array([[[1,2,3,4]]])
another_type_array

array([[[1, 2, 3, 4]]])

In [18]:
another_type_array.shape

(1, 1, 4)

In [19]:
another_type_array.ndim

3

### Creating a big array

In [24]:
a_big=np.array([[[[[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]]]]])

In [25]:
a_big

array([[[[[[1, 2, 3, 4],
           [1, 2, 3, 4],
           [1, 2, 3, 4],
           [1, 2, 3, 4],
           [1, 2, 3, 4]]]]]])

In [26]:
a_big.ndim

6

In [27]:
a_big.shape

(1, 1, 1, 1, 5, 4)

In [28]:
a_big.size

20

In [37]:
a_big[0][0][0][0][1][1]

2

### FILLING ARRAYS

#### np.full

##### by using full function for example,we can fill anarray of a certain shape with same number. here we create a 3*5*4 matrix which will be filled with sevens

In [53]:
a_full=np.full((5,5,5),5)
a_full

array([[[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]])

In [54]:
a_full.ndim

3

### ZEROS AND ONES

#### For thr case that we want arrays full of zeros or ones, we even have specific functions 

In [56]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
b=np.ones((5,3,4))
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [61]:
a.ndim

2

In [62]:
b.ndim

3